apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: intelligent-workflows

bases:
  - ../../base

namePrefix: prod-

commonLabels:
  environment: production

replicas:
  - name: workflows-api
    count: 3

images:
  - name: ghcr.io/davidmoltin/intelligent-workflows
    newTag: latest

configMapGenerator:
  - name: workflows-api-config
    behavior: merge
    literals:
      - APP_ENV=production
      - LOG_LEVEL=warn

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: workflows-api
