apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: intelligent-workflows

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
  - servicemonitor.yaml

commonLabels:
  app.kubernetes.io/name: intelligent-workflows
  app.kubernetes.io/component: api
  app.kubernetes.io/managed-by: kustomize

images:
  - name: ghcr.io/davidmoltin/intelligent-workflows
    newTag: latest
