apiVersion: v1
kind: ServiceAccount
metadata:
  name: workflows-api
  namespace: intelligent-workflows
  labels:
    app: workflows-api

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflows-api
  namespace: intelligent-workflows
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflows-api
  namespace: intelligent-workflows
subjects:
  - kind: ServiceAccount
    name: workflows-api
    namespace: intelligent-workflows
roleRef:
  kind: Role
  name: workflows-api
  apiGroup: rbac.authorization.k8s.io
