apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: intelligent-workflows-dev

bases:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: development

replicas:
  - name: workflows-api
    count: 1

images:
  - name: ghcr.io/davidmoltin/intelligent-workflows
    newTag: develop

configMapGenerator:
  - name: workflows-api-config
    behavior: merge
    literals:
      - APP_ENV=development
      - LOG_LEVEL=debug
      - RATE_LIMIT_REQUESTS_PER_SECOND=1000

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: workflows-api
